site_name: ollog
site_url: http://localhost:8000/guide/
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

nav:
  - Home: index.md
  - Deployment: deployment.md
  - Getting Started: getting-started.md
  - Admin Guide: admin-guide.md
  - API Reference: api-reference.md
  - ADIF Field Reference: adif-field-reference.md
  - Troubleshooting: troubleshooting.md
